site_name: WONDER
repo_url: https://github.com/ntonnaett/wonder/
nav:
  - Home: index.md
  - Manual:
    - CWonder: Manual/CWonder.md
    - TWonder: Manual/TWonder.md
    - XWonder: Manual/XWonder.md
  - OSC Commands:
    - Generic: OSC/OSC.md
    - CWonder: OSC/CWonder.md
    - TWonder: OSC/TWonder.md
    - XWonder: OSC/XWonder.md
  - Installation:
    - Build: Installation/Build.md
    - Configuration: Installation/Config.md
  - About:
    - Wave Field Synthesis: About/WFS.md
    - Authors: About/Authors.md
    - License: About/License.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - def_list
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
