site_name: WONDER
repo_url: https://github.com/ntonnaett/wonder-lite/
nav:
  - Home: index.md
  - Manual:
    - CWonder: Manual/CWonder.md
    - TWonder: Manual/TWonder.md
    - XWonder: Manual/XWonder.md
  - Build: Build.md
  - Configuration: Config.md
  - About:
    - Authors: About/Authors.md
    - License: About/License.md
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - def_list
